export const APACHE_STATE_TYPE = {
  STOPPED: 'STOPPED',
  STARTED: 'STARTED'
}

export const DIRECTIVE_TYPE = {
  ROOT: 'ROOT',
  SCOPED: 'SCOPED',
  PLAIN: 'PLAIN',
  BLANK_LINE: 'BLANK_LINE',
  COMMENT: 'COMMENT',
  FAKE_SCOPE_PARAMETER: 'FAKE_SCOPE_PARAMETER'
}

export const LOG_MESSAGE_TYPE = {
  INFO: 'INFO',
  ERROR: 'ERROR'
}
