export const APACHE_STATE_TYPE = {
  STOPPED: 'STOPPED',
  RUNNING: 'RUNNING',
  STARTED: 'STARTED'
}

export const DIRECTIVE_TYPES = {
  SCOPED: 'SCOPED',
  PLAIN: 'PLAIN',
  BLANK_LINE: 'BLANK_LINE',
  COMMENT: 'COMMENT'
}
